import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Playback Policy</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href='https://livepeer.studio'>Livepeer Studio</a> Playback Policy
        </h1>
        <div className={styles.grid}>
          <a className={styles.card} href='admin'>
            <h2>Admin Console &rarr;</h2>
          </a>
          <a className={styles.card} href='login'>
            <h2>Watch Streams &rarr;</h2>
          </a>
        </div>
      </main>
    </div>
  );
};

export default Home;
