import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { ConnectKitButton } from 'connectkit'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Plyaback Policy</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href='https://livepeer.studio'>Livepeer Studio</a> Playback Policy
        </h1>

        
        <ConnectKitButton />
        

        <div className={styles.grid}>
          <div className={styles.card}>
          Hello
          </div>
        </div>
      </main>
    </div>
  );
}

export default Home
