import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Router, { useRouter } from 'next/router';
import { ConnectKitButton } from 'connectkit';
import styles from '../styles/Home.module.css';
import { url } from 'inspector';

const Home: NextPage = () => {

  const privateKey = process.env.PRIVATE_KEY;


  async function authorize() {



    // await router.push('/view')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Plyaback Policy</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href='https://livepeer.studio'>Livepeer Studio</a> Playback Policy
        </h1>
        <ConnectKitButton />
        <div className={styles.grid}>
          <a className={styles.card} href='stream'>
            <h2>Restrict a Stream &rarr;</h2>
          </a>
          <button className={styles.card} onClick={authorize}>
            <h2>View Stream &rarr;</h2>
          </button>
        </div>
      </main>
    </div>
  );
};

export default Home;
